version: '3'


vars:
  mx: "sc-meta"
  DOTENV_FILENAME: .env
  Wallet: "./wallets/hiro.pem"

env:
  DOTENV_FILENAME: "{{.DOTENV_FILENAME}}"

tasks:
  build:
    cmds:
      - "{{.mx}} all build"

  wallet:
    cmds:
      - "{{.mx}} wallet new --format pem --outfile {{.Wallet}}"

  deploy:
    cmds:
      - "mxpy contract deploy --pem {{.Wallet}} --gas-limit=60000000 --bytecode output/lottery.wasm"
