[package]
name = "lotterytoken"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.multiversx-sc]
version = "0.56.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.56.1"

[lib]
path = "src/token.rs"