name: CI

on:
  push:
    branches:
      - main
      - "*"
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: ./.github/workflows/contracts.yml
    with:
      rust-toolchain: stable
      #      mx-scenario-go-version: v2.0.0
    #      enable-interactor-tests: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
